### ISSUE TITLE
Initiatives links are not properly working

### ISSUE THREAD

**Issue by Parmesh119** [ravichanga101/charusat-v5#106]
The links that are in Initiatives section either redirecting on home page or the routing is ./comming-soon.

@Nachi1502, please try to fix it. see the routing

![image](https://github.com/ravichanga101/charusat-v5/assets/101285245/72d89319-aa3f-431d-bb32-ed214bd8f044)
![image](https://github.com/ravichanga101/charusat-v5/assets/101285245/02f65275-afdb-4871-a736-526f22dadb37)
![image](https://github.com/ravichanga101/charusat-v5/assets/101285245/609d3a13-9850-4e3b-af73-08a7bd3e2d4b)

**Comment by ravichanga101** [comment]
issue resolved please check again

**Comment by ravichanga101** [comment]
done
