### ISSUE TITLE
CSRTC link is not working on ac.in but working on localhost

### ISSUE THREAD

**Issue by Parmesh119** [ravichanga101/charusat-v5#107]
![image](https://github.com/ravichanga101/charusat-v5/assets/101285245/685ef7b2-9ab3-4b60-82c7-639594b79d31)

![image](https://github.com/ravichanga101/charusat-v5/assets/101285245/c61cb40e-5506-40b5-905f-da79f75771a3)

**Comment by ravichanga101** [comment]
Resolved please check it again

**Comment by ravichanga101** [comment]
done

**Comment by ravichanga101** [comment]
done
