### ISSUE TITLE
Footer quick links are not working

### ISSUE THREAD

**Issue by Parmesh119** [ravichanga101/charusat-v5#108]
![image](https://github.com/ravichanga101/charusat-v5/assets/101285245/fb8a4d11-3d44-4740-b242-a99ef52053a3)
![Screenshot from 2024-03-18 23-20-43](https://github.com/ravichanga101/charusat-v5/assets/101285245/f48e4b89-0f2a-47a4-9b75-833129ddf314)

**Comment by ravichanga101** [comment]
issue resolved please check it again

**Comment by ravichanga101** [comment]
fixed
