### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by Parmesh119** [ravichanga101/charusat-v5#113]
## Page not found

![image](https://github.com/ravichanga101/charusat-v5/assets/101285245/ec26796c-e0b5-44e4-80fb-3623855959c6)
[Screencast from 19-03-24 11:42:32 PM IST.webm](https://github.com/ravichanga101/charusat-v5/assets/101285245/1d31aab3-f16f-464b-b7a4-698eb9ba4a56)

**Comment by ravichanga101** [comment]
issue resolved please check it again
