### ISSUE TITLE
Governing Body / Board of Management

### ISSUE THREAD

**Issue by Jalpeshv** [ravichanga101/charusat-v5#150]
Shri Surendra Patel : He is Chairperson in Governing Body & Board of Management

Dr. R V Upadhyay : He is Member in Governing Body & Board of Management

Dr. Y P Kosta : He is Member in Governing Body

Dr. M Balaganapathy : He is Member in Board of Management (he should be before Member Secretary)

**Comment by ravichanga101** [comment]
done
