### ISSUE TITLE
Navbar CSS is not proper

### ISSUE THREAD

**Issue by Parmesh119** [ravichanga101/charusat-v5#16]
![Screenshot from 2024-03-10 18-09-50](https://github.com/ravichanga101/charusat-v5/assets/101285245/d514ffd0-4aa0-4c08-9e7b-04b09502cf24)

## The support-charusat button is not properly fitted

**Comment by Parmesh119** [comment]
@ravichanga101 
sir please add the 
## padding: 11px 0;
instead of 
## padding: 8px 0;
in the file style.css, line number 5042 in order to solve this issue

**Comment by Nachi1502** [comment]
Changed
