### ISSUE TITLE
Fav Icon Not Displaying

### ISSUE THREAD

**Issue by ravichanga101** [ravichanga101/charusat-v5#3]
Fav Icon Not Displaying

**Comment by Parmesh119** [comment]
![Screenshot from 2024-03-01 14-53-09](https://github.com/ravichanga101/charusat-v5/assets/101285245/24cc689e-ab72-4cd5-a13b-0a9389476638)


# Favicon is not properly displaying; try to fix it.

![Screenshot from 2024-03-01 15-03-13](https://github.com/ravichanga101/charusat-v5/assets/101285245/d67eee36-3622-49dd-8ad7-a1a170118234)

# Although the path is perfect.

**Comment by Parmesh119** [comment]
@ravichanga101 
Sir please add this link in the file layout.js at the line number 20

https://i.ibb.co/DK5QrLM/Logo.png

in order to render the favicon
