### ISSUE TITLE
Charusat people section loading should be smooth

### ISSUE THREAD

**Issue by Parmesh119** [ravichanga101/charusat-v5#31]
When we came back from Board of Management to Governing Body, the padding is more in Governing Body compare to Board of Management
[Screencast from 13-03-24 10:35:49 PM IST.webm](https://github.com/ravichanga101/charusat-v5/assets/101285245/f1d24098-6d27-4bf3-9b7e-26884b8062aa)

**Comment by Nachi1502** [comment]
Done
