### ISSUE TITLE
Not responsive in tablet view

### ISSUE THREAD

**Issue by Parmesh119** [ravichanga101/charusat-v5#40]
![latest](https://github.com/ravichanga101/charusat-v5/assets/101285245/a2cfd868-1c4d-46cb-af9b-037287c0d8cc)

**Comment by Nachi1502** [comment]
Check again

**Comment by Parmesh119** [comment]
![laptop](https://github.com/ravichanga101/charusat-v5/assets/101285245/bbbfc9ab-6ce8-4de7-995d-d3459b6d93d4)

## not done yet

**Comment by ravichanga101** [comment]
done
