### ISSUE TITLE
Create a Section for HoW to Reach Us

### ISSUE THREAD

**Issue by Jalpeshv** [ravichanga101/charusat-v5#46]
Add following details with map and section name should be how to reach us.
Flying in:
The nearest international airport is Ahmedabad which is two hours drive by road. There are daily domestic flights from Mumbai and Delhi. Indian Airlines, Jet Airways and Spice Jet fly to Ahmedabad. There are direct international flights to Ahmedabad from Dubai, Abu Dhabi, Muscat, Doha Qatar, Bahrain, Kuwait, and USA. Prepaid taxis are available at the Ahmedabad airport.

By road:
Changa is well connected with the major cities in Gujarat, Maharastra, Rajasthan, etc. Buses runs between Ahmedabad and Nadiad/Anand frequently.

By train:
The closest railway stations are at Nadiad (12 kms from Changa) and Anand (22 kms from Changa). Delhi (to the north) and Mambai (to the south) are linked to Nadiad/Anand stations. Anand station is connected to Bangalore, Chennai, Delhi, Goa, Calicut, Cochin, Trivandrum, Mumbai and other major cities. For more information check: www.indianrail.gov.in

**Comment by ravichanga101** [comment]
done
