### ISSUE TITLE
Page for timings : NEEDS TO BE DISCUSSED

### ISSUE THREAD

**Issue by Jalpeshv** [ravichanga101/charusat-v5#49]
Page should have contents like.
Title - Timings
Description- The University and Institute offices are open as per the following schedule. The offices remain closed on the second and fourth Saturday and public holidays.
Table for timings - CHARUSAT University - 09:00 am to 04:30 pm
outside table - * Timings are subject to change at the discretion of the management.

Add this tab at the footer.

**Comment by ravichanga101** [comment]
done
